#!/bin/sh

amixer --quiet sset 'PCM' 0%

mplayer http://radiobonheur.ice.infomaniak.ch/radiobonheur-128-1.mp3 -af volume=-37.5 -endpos $1 -quiet &

i=60
while [[ $i -le 100 ]]
do 
  amixer --quiet sset 'PCM' $i%
  usleep 250000
  let i=i+1
done

